#!/bin/sh
if [ "$(id -u)" -ne 0 ]; then
    echo "You may need to run this script as sudo if you see permission errors"
fi
if [ ! -z "${SUDO_USER}" ]; then
    user=${SUDO_USER}
else
    user=`whoami`
fi
set -e
cat << EOF > /etc/udev/rules.d/99-oe4t.rules
# Jetson TK1
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7140", GROUP="plugdev"
# Jetson TX1
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7721", GROUP="plugdev"
# Jetson TX2
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7c18", GROUP="plugdev"
# Jetson TX2i
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7018", GROUP="plugdev"
# Jetson TX2-4GB
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7418", GROUP="plugdev"
# Jetson AGX Xavier
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7019", GROUP="plugdev"
# Jetson Xavier NX
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7e19", GROUP="plugdev"
# Jetson Nano
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7f21", GROUP="plugdev"
# Jetson Orin AGX (P3701-0000 Developer Kit module), (P3701-0005 with 64GB), (P3701-0008 with 64GB)
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7023", GROUP="plugdev"
# Jetson Orin AGX (P3701-0004 with 32GB)
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7223", GROUP="plugdev"
# Jetson Orin NX (P3767-0000 with 16GB)
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7323", GROUP="plugdev"
# Jetson Orin NX (P3767-0001 with 8GB)
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7423", GROUP="plugdev"
# Jetson Orin Nano (P3767-0003 and P3767-0005 with 8GB)
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7523", GROUP="plugdev"
# Jetson Orin Nano (P3767-0004 with 4GB)
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7623", GROUP="plugdev"
EOF
udevadm control --reload
echo "udev settings applied, please disconnect/reconnect your device"
set +e
groups ${user} | grep "plugdev" > /dev/null 2>&1
rc=$?
if [ $rc -ne 0 ]; then
    echo "Please add ${user} to plugdev using:"
    echo "sudo usermod -a -G plugdev  ${user}"
    echo "Then apply to your user by logging back into the session or running"
    echo "newgrp plugdev"
fi
